- hosts: ansible-terraform
  tasks:
  - name: instalando python e venv
    apt:
      pkg:
      - python3
      - virtualenv
      update_cache: yes
    become: yes
  - name: instalando dependencias com pip
    pip: 
      virtualenv: /home/ubuntu/tcc/venv
      name: 
      - django
      - djangorestframework


     
