- hosts: ansible-terraform
  tasks:
  - name: criando arquivo index.html
    copy: 
      dest: /home/ubuntu/index.html
      content: <h1> criação automatizada pelo ansible <h1>
  - name: criando servidor
    shell: "nohup busybox httpd -f -p 8080 &"
